### Access 
### Sign Up
POST http://localhost:3030/api/v1/access/sign-up
Content-Type: application/json

{
    "email": "test9@gmail.com",
    "password": "123"
}

### Login
POST http://localhost:3030/api/v1/access/login
Content-Type: application/json

{
    "option": "test9@gmail.com",
    "password": "123"
}

### Logout
DELETE  http://localhost:3030/api/v1/access/logout
Content-Type: application/json

### Shop

### Register Booth
POST  http://localhost:3030/api/v1/access/logout
Content-Type: application/json

# {
#     "userId": 2
#     "province_code": "test@gmail.com",
# }


### Location 
GET http://localhost:3030/api/v1/address
### Province 
GET http://localhost:3030/api/v1/address/procince

### District 
GET http://localhost:3030/api/v1/address/district/68

### Ward 
GET http://localhost:3030/api/v1/address/ward/672

### Search
GET http://localhost:3030/api/v1/address/search/?place=Đà Lạt

### User
GET http://localhost:3030/api/v1/customer

### Get my info 
GET http://localhost:3030/api/v1/customer/profile
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjYsImlhdCI6MTcyNTM2NjIzNywiZXhwIjoxNzI2MjMwMjM3fQ.pkkbpx-eL1-uzbGuYB-1mlssgPThfCf71b1CA6MABiA

### update info
PUT http://localhost:3030/api/v1/customer/update-profile
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjYsImlhdCI6MTcyNTM2NjIzNywiZXhwIjoxNzI2MjMwMjM3fQ.pkkbpx-eL1-uzbGuYB-1mlssgPThfCf71b1CA6MABiA

{
    "phone_number": "12323453456",
    "last_name": "Nguyen",
    "first_name": "Thanh"
}

### add shipping address
POST http://localhost:3030/api/v1/customer/add-shipping-address
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE1LCJpYXQiOjE3MjUzNjY2NTAsImV4cCI6MTcyNjIzMDY1MH0.psy6PlfkJFcac3RjPQRKxCs8RWkSqwA1IItd-2VAiWY

{
    "ward_code": "24796",
    "province": "Tỉnh Lâm Đồng",
    "district": "Thành phố Đà Lạt",
    "ward": "Phường 10",
    "address": "999 Trần Hưng Đạo",
    "phone_number": "012323423498765"
}

### get all customer shipping address
GET http://localhost:3030/api/v1/customer/shipping-addresses
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE1LCJpYXQiOjE3MjUzNjY2NTAsImV4cCI6MTcyNjIzMDY1MH0.psy6PlfkJFcac3RjPQRKxCs8RWkSqwA1IItd-2VAiWY

### update image -- 

# PUT http://localhost:3030/api/v1/customer/update-image
# Content-Type: multipart/form-data
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE3LCJpYXQiOjE3MjUzMzM1ODYsImV4cCI6MTcyNjE5NzU4Nn0.MT29SyEW9k4BPrwJRipYNy8PjHTuHVpetuhrBsfJIdU

# --boundary
# Content-Disposition: form-data; name="customerImage"; filename="test-img.jpg"
# Content-Type: image/jpeg

# < C:\Users\middm\OneDrive\Desktop\NodeJS\TMD\server\public\images\test-img.jpg
# --boundary--
### SHOP
GET http://localhost:3030/api/v1/shop

### register shop
POST http://localhost:3030/api/v1/shop/register
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE4LCJpYXQiOjE3MjUzNjkyMTAsImV4cCI6MTcyNjIzMzIxMH0.j0pIQ_-VM1vUHYfEXwQCOMijzFjLAvZYR2oCdy7W0-0

{
    "name": "shop test 9"
}

### get shop info for owner
GET http://localhost:3030/api/v1/shop/profile
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE4LCJpYXQiOjE3MjUzNjkyMTAsImV4cCI6MTcyNjIzMzIxMH0.j0pIQ_-VM1vUHYfEXwQCOMijzFjLAvZYR2oCdy7W0-0

### add product shop info for owner
POST http://localhost:3030/api/v1/shop/add-product
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE4LCJpYXQiOjE3MjUzNjkyMTAsImV4cCI6MTcyNjIzMzIxMH0.j0pIQ_-VM1vUHYfEXwQCOMijzFjLAvZYR2oCdy7W0-0

{
    "name": "San pham 1",
    "description": "Day la san pham 1 của shop 9",
    "price": 100000,
    "sale_price": 80000,
    "stock_quantity": 100,
    "brand_id": 10,
    "category_ids": [1, 2, 3]
}
### update image -- 

# PUT http://localhost:3030/api/v1/shop/update-image
# Content-Type: multipart/form-data
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE3LCJpYXQiOjE3MjUzMzM1ODYsImV4cCI6MTcyNjE5NzU4Nn0.MT29SyEW9k4BPrwJRipYNy8PjHTuHVpetuhrBsfJIdU

# --boundary
# Content-Disposition: form-data; name="customerImage"; filename="test-img.jpg"
# Content-Type: image/jpeg

# < C:\Users\middm\OneDrive\Desktop\NodeJS\TMD\server\public\images\test-img.jpg
# --boundary--

### view product shop info for owner

### add product images
POST http://localhost:3030/api/v1/shop/update-product-images
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE4LCJpYXQiOjE3MjUzNjkyMTAsImV4cCI6MTcyNjIzMzIxMH0.j0pIQ_-VM1vUHYfEXwQCOMijzFjLAvZYR2oCdy7W0-0

{
    
    "name": "San pham 1",
    "description": "Day la san pham 1 của shop 9",
    "price": 100000,
    "sale_price": 80000,
    "stock_quantity": 100,
    "brand_id": null,
    "category_id": null
}